### ISSUE TITLE
完成安装后能打开bilibili却打不开百度等其他网站

### ISSUE THREAD

**Issue by zyongjunpro** [Titzanyic/Clover#6]
您好，很抱歉打扰您，我使用了和你一样的机型dell 3080mff ，cpu为10100，固态为光威奕pro。
在安装完成后Safari浏览器能够打开bilibili的网站，却不能打开百度、必应等搜索网站，这令我十分困惑，希望能从您这里得到解答，感谢！
下面是相关截图
![IMG_20220428_220308](https://user-images.githubusercontent.com/43309299/165771520-39cdeb37-09b7-4257-be84-dc98dad5669a.jpg)
![image](https://user-images.githubusercontent.com/43309299/165772173-ec5879c4-98a1-4773-a371-73ac92a97c29.png)
![image](https://user-images.githubusercontent.com/43309299/165772235-2db01572-c562-4f1c-aeb4-ba4c2cdc5f24.png)

**Comment by zyongjunpro** [comment]
> 您好，很抱歉打扰您，我使用了和你一样的机型dell 3080mff ，cpu为10100，固态为光威奕pro。 在安装完成后Safari浏览器能够打开bilibili的网站，却不能打开百度、必应等搜索网站，这令我十分困惑，希望能从您这里得到解答，感谢！ 下面是相关截图 ![IMG_20220428_220308](https://user-images.githubusercontent.com/43309299/165771520-39cdeb37-09b7-4257-be84-dc98dad5669a.jpg) ![image](https://user-images.githubusercontent.com/43309299/165772173-ec5879c4-98a1-4773-a371-73ac92a97c29.png) ![image](https://user-images.githubusercontent.com/43309299/165772235-2db01572-c562-4f1c-aeb4-ba4c2cdc5f24.png)

**Comment by zhangyongcun** [comment]
看起来像是网络问题，请用命令行 `ping baidu.com` 试试，或者更换 Chrome 浏览器试试。

**Comment by zyongjunpro** [comment]
> 看起来像是网络问题，请用命令行 `ping baidu.com` 试试，或者更换 Chrome 浏览器试试。

十分感谢您的回复，经检查后发现是路由器的问题，重新刷入固件后可以正常使用了。
最后，感谢您的efi。
